name: Update Time Tracking Summary

on:
  push:
    paths:
      - 'manHour/data/actual/*.csv'
      - 'manHour/data/planned.csv'
  workflow_dispatch:  # 手動実行も可能

jobs:
  update-summary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 全履歴を取得
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          
      - name: Update time tracking summary
        run: python manHour/scripts/update_summary.py
        
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add manHour/data/summary.csv
          git diff --quiet && git diff --staged --quiet || git commit -m "自動更新: 作業時間サマリー"
          git push